[font]
size = 16.0

[window]
decorations = "full"

[window.dimensions]
columns = 135
lines = 30

[[keyboard.bindings]]
chars = "\u001B[1;5D"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;5C"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"
